export { default as Home } from './Home';
export { default as Landing } from './Landing';
export { default as NewAccount } from './NewAccount';
export { default as Login } from './Login';
export { default as ValidateOTP } from './ValidateOTP';
export { default as ForgetPassword } from './ForgetPassword';
export { default as ChangePassword } from './ChangePassword';
export { default as ResetPassword } from './ResetPassword';
export { default as MenuList } from './MenuList';
export { default as Jobs } from './Jobs';
export { default as Branches } from './Branches';
export { default as Delivery } from './Delivery';
export { default as Privacy } from './Privacy';
export { default as Payment } from './Payment';
export { default as Terms } from './Terms';
export { default as Refund } from './Refund';
export { default as Profile } from './Profile';
export { default as Orders } from './Orders';
export { default as User } from './User';
export { default as About } from './About';
export { default as ContactUs } from './ContactUs';
export { default as Events } from './Events';
export { default as News } from './News';
export { default as SingleEventPage } from './SingleEventPage';
export { default as OrderDonePage } from './OrderDonePage';
export { default as ProceedPage } from './ProceedPage';
// export { default as TrackOrder } from './TrackOrder';
// export { default as OrderTrack } from './OrderTrack';
// export { default as ProceedDelivery } from './ProceedDelivery';
// export { default as PaymentDetails } from './PaymentDetails';
export { default as MenuCategory } from './MenuCategory';
export { default as VerifyEmail } from './VerifyEmail';
export { default as MyAddress } from './MyAddress';
export { default as NewAddress } from './NewAddress';
export { default as SingleOrder } from './SingleOrder';
export { default as SingleNewsPage } from './SingleNewsPage';
export { default as UpdateAddress } from './UpdateAddress';
export { default as Articles } from './Articles';
export { default as SingleArticlePage } from './SingleArticlePage';
