export {default as Home} from "./Home"
export {default as Landing} from "./Landing"
export {default as NewAccount} from "./NewAccount"
export {default as Login} from "./Login"
export {default as ValidateOTP} from "./ValidateOTP"
export {default as ForgetPassword} from "./ForgetPassword"